# Generated by Django 5.2.16 on 2026-08-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user",
            new_name="author",
        ),
    ]
