# Generated by Django 5.2.16 on 2026-08-24 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_image_user_username_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
